COUCHDB_ROOT = ..
include $(COUCHDB_ROOT)/Makefile.bootstrap
include $(COUCHDB_MAKED)/core
include $(COUCHDB_MAKED)/metadocs
include $(COUCHDB_MAKED)/build-targets
include Makefile.depends

BASE_DOCUMENT = couchdb-release
BASE_VERSION = 1.3
EPUB_ICON = images/epub-icon.png
